import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { Message } from '../types/index.js';

export interface DocExport {
  filePath: string;
  content: string;
  sections: DocSection[];
}

export interface DocSection {
  title: string;
  content: string;
  type: 'decision' | 'solution' | 'explanation' | 'code' | 'tool_usage' | 'architecture';
}

export async function exportConversationToDocs(
  messages: Message[],
  cwd: string,
  title?: string
): Promise<DocExport> {
  const sections = extractSections(messages);
  const docContent = buildMarkdown(sections, title ?? 'Session Documentation');

  const filename = `session-${new Date().toISOString().slice(0, 10)}-${Date.now().toString(36)}.md`;
  const docsDir = join(cwd, '.spearcode', 'docs');
  await mkdir(docsDir, { recursive: true });

  const filePath = join(docsDir, filename);
  await writeFile(filePath, docContent, 'utf-8');

  return { filePath, content: docContent, sections };
}

function extractSections(messages: Message[]): DocSection[] {
  const sections: DocSection[] = [];

  let currentCode: { lang: string; code: string } | null = null;
  let decisions: string[] = [];
  let solutions: string[] = [];
  let explanations: string[] = [];
  let toolUsages: string[] = [];

  for (const msg of messages) {
    if (msg.role !== 'assistant' || !msg.content) continue;

    const content = msg.content;

    // Extract decisions (when AI says "I'll do X", "let's use X", etc.)
    const decisionPatterns = [
      /(?:I'?ll|let'?s|going to|decided? to|use|choose|prefer)\s+(.{10,100})/gi,
      /(?:approach|strategy|plan|decision)[:\s]+(.{10,200})/gi,
    ];
    for (const pattern of decisionPatterns) {
      const matches = content.matchAll(pattern);
      for (const m of matches) {
        decisions.push(m[1].trim());
      }
    }

    // Extract solutions
    if (/fixed|solved|resolved|here'?s the fix|solution/i.test(content)) {
      const fixMatch = content.match(/(?:fixed|solved|resolved)[:\s]*([\s\S]{10,500}?)(?:\n\n|\.\s|$)/i);
      if (fixMatch) solutions.push(fixMatch[1].trim());
    }

    // Extract code blocks
    const codeBlocks = content.matchAll(/```(\w*)\n([\s\S]*?)```/g);
    for (const block of codeBlocks) {
      if (block[2].trim().length > 20) {
        currentCode = { lang: block[1] || 'text', code: block[2].trim() };
        sections.push({
          title: `Code: ${block[1] || 'snippet'}`,
          content: block[2].trim(),
          type: 'code',
        });
      }
    }

    // Extract explanations
    const explainMatch = content.match(/(?:this|it|the function|the code)\s+(?:works by|does|handles|implements|is responsible for)\s+([\s\S]{20,300}?)(?:\.|$)/i);
    if (explainMatch) {
      explanations.push(explainMatch[1].trim());
    }
  }

  // Build summary sections
  if (decisions.length) {
    sections.unshift({
      title: 'Key Decisions',
      content: decisions.slice(0, 10).map((d) => `- ${d}`).join('\n'),
      type: 'decision',
    });
  }

  if (solutions.length) {
    sections.unshift({
      title: 'Solutions Applied',
      content: solutions.slice(0, 10).map((s) => `- ${s}`).join('\n'),
      type: 'solution',
    });
  }

  if (explanations.length) {
    sections.push({
      title: 'Explanations',
      content: explanations.slice(0, 10).map((e) => `- ${e}`).join('\n'),
      type: 'explanation',
    });
  }

  // Extract tool usage
  const toolMessages = [] as Message[];
  for (const msg of messages) {
    if (msg.role === 'tool' && msg.content) {
      toolMessages.push(msg);
    }
  }

  if (toolMessages.length) {
    const toolSummary = toolMessages
      .filter((m) => !m.content.includes('Error'))
      .slice(0, 20)
      .map((m) => `- Used tool: ${m.content.slice(0, 100)}`)
      .join('\n');

    sections.push({
      title: 'Tools Used',
      content: toolSummary,
      type: 'tool_usage',
    });
  }

  return sections;
}

function buildMarkdown(sections: DocSection[], title: string): string {
  const lines: string[] = [];

  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`Generated by SpearCode on ${new Date().toISOString()}`);
  lines.push('');

  // Table of contents
  lines.push('## Table of Contents');
  lines.push('');
  for (const section of sections) {
    const anchor = section.title.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    lines.push(`- [${section.title}](#${anchor})`);
  }
  lines.push('');

  // Sections
  for (const section of sections) {
    lines.push(`## ${section.title}`);
    lines.push('');
    lines.push(section.content);
    lines.push('');
  }

  return lines.join('\n');
}

export async function exportToReadme(
  messages: Message[],
  cwd: string,
  projectName: string
): Promise<string> {
  const sections = extractSections(messages);

  const lines: string[] = [];
  lines.push(`# ${projectName}`);
  lines.push('');

  // Find architecture explanations
  const archSections = sections.filter((s) =>
    s.type === 'explanation' || s.type === 'architecture'
  );
  if (archSections.length) {
    lines.push('## Architecture');
    lines.push('');
    for (const s of archSections) {
      lines.push(s.content);
      lines.push('');
    }
  }

  // Find decisions
  const decisions = sections.filter((s) => s.type === 'decision');
  if (decisions.length) {
    lines.push('## Technical Decisions');
    lines.push('');
    for (const s of decisions) {
      lines.push(s.content);
      lines.push('');
    }
  }

  const readmePath = join(cwd, 'README.spearcode.md');
  await writeFile(readmePath, lines.join('\n'), 'utf-8');

  return readmePath;
}
