#!/usr/bin/env bash
# Install a robust GUI desktop launcher for SpearCode (Linux / GNOME et co.).
#
# SpearCode is a terminal (TUI) app: clicking a plain ".desktop" that just
# runs the binary does nothing visible, because the desktop/file-manager
# launch scope has no terminal and no keyboard. This installs a wrapper
# that opens a real terminal window, plus a trusted+executable .desktop in
# the application menu AND on the Desktop, with full logging so a failed
# click can always be diagnosed.
#
# Idempotent — safe to re-run after every build/upgrade.
#
#   bash scripts/install-desktop-launcher.sh [path-to-spearcode-binary]
#
# Binary resolution order:
#   1. $1 argument            2. $SPEARCODE_BIN
#   3. <repo>/release/spearcode-linux-x64   (local source build)
#   4. spearcode on $PATH                   (install.sh / .deb)
set -euo pipefail

here="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
repo="$(cd "$here/.." && pwd)"

resolve_bin() {
  local c
  for c in "${1:-}" "${SPEARCODE_BIN:-}" \
           "$repo/release/spearcode-linux-x64" \
           "$(command -v spearcode 2>/dev/null || true)"; do
    [ -n "$c" ] && [ -x "$c" ] && { readlink -f "$c"; return 0; }
  done
  return 1
}

BIN="$(resolve_bin "${1:-}")" || {
  echo "✗ Aucun binaire SpearCode trouvé." >&2
  echo "  Construis-le (npm run build:bin -- node20-linux-x64) ou passe le chemin :" >&2
  echo "  bash scripts/install-desktop-launcher.sh /chemin/vers/spearcode" >&2
  exit 1
}
echo "• Binaire     : $BIN"

APPS="$HOME/.local/share/applications"
BINW="$HOME/.local/bin"
ICONS="$HOME/.local/share/icons/hicolor/256x256/apps"
DESKTOP_DIR="$(xdg-user-dir DESKTOP 2>/dev/null || echo "$HOME/Desktop")"
mkdir -p "$APPS" "$BINW" "$ICONS" "$DESKTOP_DIR"

# ── 1. Hardened terminal wrapper ─────────────────────────────────────────
LAUNCH="$BINW/spearcode-launch.sh"
cat > "$LAUNCH" <<EOF
#!/usr/bin/env bash
# SpearCode desktop launcher — opens a real terminal and runs the TUI.
# Generated by scripts/install-desktop-launcher.sh — do not edit by hand.
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:\$PATH"
LOG_DIR="\${XDG_CACHE_HOME:-\$HOME/.cache}/spearcode"
mkdir -p "\$LOG_DIR" 2>/dev/null
LOG="\$LOG_DIR/launch.log"
log() { echo "[\$(date '+%F %T')] \$*" >>"\$LOG" 2>/dev/null; }
{ echo; echo "===== launcher start (pid \$\$) ====="; } >>"\$LOG" 2>/dev/null
log "PATH=\$PATH"
log "DISPLAY=\${DISPLAY:-<none>} WAYLAND_DISPLAY=\${WAYLAND_DISPLAY:-<none>} DESKTOP=\${XDG_CURRENT_DESKTOP:-<none>}"

BIN="\${SPEARCODE_BIN:-$BIN}"
[ -x "\$BIN" ] || BIN="\$(command -v spearcode 2>/dev/null || echo "\$BIN")"
WORKDIR="\${SPEARCODE_WORKDIR:-\$HOME}"
log "BIN=\$BIN  WORKDIR=\$WORKDIR"

fail() {
  log "FATAL: \$1"
  notify-send "SpearCode" "\$1" 2>/dev/null
  zenity --error --no-wrap --title="SpearCode" --text="\$1\n\nDétails : \$LOG" 2>/dev/null \\
    || xmessage -center "SpearCode : \$1 (\$LOG)" 2>/dev/null
  exit 1
}
[ -x "\$BIN" ] || fail "Binaire SpearCode introuvable :\n\$BIN"

INNER="cd \$(printf %q "\$WORKDIR") 2>/dev/null; \$(printf %q "\$BIN"); ec=\\\$?; echo; echo \"[SpearCode terminé (code \\\$ec) — Entrée pour fermer]\"; read -r"

try_term() {
  log "TRY: \$1"
  setsid "\$@" >>"\$LOG" 2>&1 &
  local pid=\$! rc
  sleep 2
  if kill -0 "\$pid" 2>/dev/null; then log "OK (running): \$1"; return 0; fi
  wait "\$pid"; rc=\$?; log "client rc=\$rc: \$1"; [ "\$rc" -eq 0 ]
}

command -v gnome-terminal       >/dev/null 2>&1 && try_term gnome-terminal --title="SpearCode" -- bash -lc "\$INNER" && exit 0
command -v kgx                  >/dev/null 2>&1 && try_term kgx -- bash -lc "\$INNER" && exit 0
command -v konsole              >/dev/null 2>&1 && try_term konsole --hold -e bash -lc "\$INNER" && exit 0
command -v xfce4-terminal       >/dev/null 2>&1 && try_term xfce4-terminal --hold -e "bash -lc '\$INNER'" && exit 0
command -v xterm                >/dev/null 2>&1 && try_term xterm -T SpearCode -e bash -lc "\$INNER" && exit 0
command -v x-terminal-emulator  >/dev/null 2>&1 && try_term x-terminal-emulator -e bash -lc "\$INNER" && exit 0

fail "Aucun émulateur de terminal trouvé.\nOuvre un terminal et lance : \$BIN"
EOF
chmod +x "$LAUNCH"
echo "• Lanceur     : $LAUNCH"

# ── 2. Icon (real one if available, else a stock terminal icon) ──────────
ICON_NAME="utilities-terminal"
for src in "$repo/release/spearcode.png" "$repo/assets/spearcode.png"; do
  if [ -f "$src" ]; then
    cp -f "$src" "$ICONS/spearcode.png"
    gtk-update-icon-cache -f "$HOME/.local/share/icons/hicolor" 2>/dev/null || true
    ICON_NAME="spearcode"
    break
  fi
done
echo "• Icône       : $ICON_NAME"

# ── 3. .desktop in the app menu + on the Desktop ─────────────────────────
desktop_contents() {
cat <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=SpearCode
Comment=Agent de code IA (terminal)
Exec=$LAUNCH
Icon=$ICON_NAME
Terminal=false
Categories=Development;
StartupNotify=true
EOF
}

APP_FILE="$APPS/spearcode.desktop"
DESK_FILE="$DESKTOP_DIR/SpearCode.desktop"
desktop_contents > "$APP_FILE"
desktop_contents > "$DESK_FILE"
chmod +x "$APP_FILE" "$DESK_FILE"

# GNOME/DING ignores a double-click on a launcher that is not "trusted".
gio set "$DESK_FILE" metadata::trusted true 2>/dev/null || true
gio set "$APP_FILE" metadata::trusted true 2>/dev/null || true
update-desktop-database "$APPS" 2>/dev/null || true

echo "• Menu        : $APP_FILE"
echo "• Bureau      : $DESK_FILE"
echo
echo "✓ Lanceur SpearCode installé. Logs de lancement : ~/.cache/spearcode/launch.log"
