export { Agent } from './core/agent.js';
export { SessionManager } from './core/session.js';
export { createAllTools, createFileTools, createSearchTools, createShellTools } from './core/tools.js';
export { createGitTools } from './core/git.js';
export { createWebTools } from './core/web.js';
export { createVisionTools } from './core/vision.js';
export { createSemanticSearchTools } from './core/semantic.js';
export { createTestGenerationTools } from './core/testGen.js';
export { createDiffTools, parseDiff, renderVisualDiff } from './core/diff.js';
export { createPRReviewTools } from './core/prReview.js';
export { createDependencyTools } from './core/deps.js';
export { createGitHubTools } from './core/github.js';
export { createExplainerTools } from './core/explainer.js';
export { createImpactTools } from './core/impact.js';
export { createAnthropicProvider, createOpenAIProvider, createOpenRouterProvider, createOllamaProvider } from './core/providers.js';
export { withRetry } from './core/retry.js';
export { analyzeProject, renderTree } from './core/context.js';
export { loadMemory, initMemory, saveMemory, appendToMemory } from './core/memory.js';
export { countTokens, countMessagesTokens, getContextWindowSize } from './core/tokens.js';
export { openInEditor } from './core/editor.js';
export { loadCustomPrompt } from './core/customPrompt.js';
export { loadWorkspaces, addWorkspace, removeWorkspace } from './core/workspace.js';
export { loadCorrections, saveCorrection, buildCorrectionsPrompt } from './core/learning.js';
export { calculateCost, summarizeCosts, formatCostSummary } from './core/cost.js';
export { PERSONAS, getPersona, listPersonas } from './core/personas.js';
export { exportConversationToDocs, exportToReadme } from './core/docs.js';
export { SessionForker } from './core/fork.js';
export { SessionSharing } from './core/sharing.js';
export { CollaborationServer, CollaborationClient } from './core/collab.js';
export { loadConfig } from './config/index.js';
// Gungnir integration is optional and OFF by default. It is intentionally
// excluded from the main entry point so the standalone surface stays pure.
// Opt in explicitly via the dedicated subpath: `import 'spearcode/gungnir'`.
export { createMcpClientManager, createToolsFromMcp } from './mcp/index.js';
export { createLspClient, createLspTools, DEFAULT_LSP_CONFIGS } from './lsp/index.js';
export { loadCommands, interpolateCommand, extractPlaceholders } from './commands/index.js';
export type * from './types/index.js';
export type { ProjectContext, FileNode, ProjectStats } from './core/context.js';
export type { Diagnostic, LspServer, LspConfig } from './lsp/index.js';
export type { CustomCommand } from './commands/index.js';
export type { ProjectMemory } from './core/memory.js';
export type { Workspace } from './core/workspace.js';
export type { Correction } from './core/learning.js';
export type { CostEntry, CostSummary } from './core/cost.js';
export type { Persona } from './core/personas.js';
export type { DocExport, DocSection } from './core/docs.js';
export type { Fork } from './core/fork.js';
export type { SharedSession } from './core/sharing.js';
export type { CollabSession, CollabParticipant, CollabMessage } from './core/collab.js';
export type { ImpactResult } from './core/impact.js';
